server:
  port: 8090
spring:
  #mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_maintenance?characterEncoding=utf8
    username: root
    password: 996562383
  #邮箱配置
  mail:
    default-encoding: utf-8
    username: 996562383@qq.com
    #swulguyattyfbded
    password: swulguyattyfbded
    host: smtp.qq.com
  #redis配置
  redis:
    host: 192.168.19.129
    port: 6379
    password: zhangyu1123..
    database: 0
    connect-timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  #文件上传大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #日志功能
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: classpath:com.zy.maintenance.bean

files:
  upload:
    path: E:/CarFile/files/




